### ISSUE TITLE
tablespace size

### ISSUE THREAD

**Issue by bigsow** [smartmarmot/DBforBIX#6]
In oracle.xml file is:
...<query time="300" item="tablespace.bytes[%1]">SELECT tablespace_name,SUM(NVL(bytes,0)) AS bytes FROM     dba_data_files GROUP BY tablespace_name</query>...
in my opinion more reliable data will be
SELECT tablespace_name,SUM(NVL(bytes,0)) AS bytes FROM dba_segments GROUP BY tablespace_name

**Comment by askifyouneed** [comment]
I will commit it.

**Comment by smartmarmot** [comment]
The dba_segments view gives you the size of the segments up to the last extent in a given tablespace.
The dba_data_files gives you the size of a given tablespace in a given data file; You might have "free space" in both a tablespace and datafile, this is why you don't get the same result. Can you please explain why is better?

**Comment by smartmarmot** [comment]
DBA_DATA_FILES=DBA_SEGMENTS+DBA_FREE_SPACE+LMT_headers

**Comment by askifyouneed** [comment]
The main goal for me to change above query is to get the picture of realible capactity which is currently used, because I need an information where I should extend my tablespace. So when I will get the trigger info that is used above 90% of tablespace capacity, I know that for sure I have to expand it.
